### ISSUE TITLE
ESP32 code problem

### ISSUE THREAD

**Issue by mbuhansen** [netmindz/balboa_GL_ML_spa_control#20]
I have got a ESP32, and try to use your code, but in validate i get error when i use it. Can you help me i am new with ESPhome..??

**Comment by netmindz** [comment]
It's likely that you are missing one of the dependencies. Are you using PlatformIO ?

Please send an example of the error

**Comment by netmindz** [comment]
Before you spend time on this project, have you confirmed which model of control unit you have? There are a few different projects for the different Balboa systems

**Comment by mbuhansen** [comment]
I have now install platformio, and try to program my ESP32, but i cant. when i load your projekt to platformio, press build in bottom i get around 20 errors, it looks like some files is missing to ES32 board. your projekt only want to make firmware to D1mini, it gives error when i connect to ESP32.  I have also try to make new projekt and move your files, but can't get it to work.

**Comment by netmindz** [comment]
To help I need to see a screenshot of the errors, the most likely issue is that it's telling you it can't find the wifi.h file with your details

**Comment by netmindz** [comment]
https://github.com/netmindz/balboa_GL_ML_spa_control/wiki/Install-Guide

**Comment by tmjo** [comment]
Another probable cause is missing libraries SoftwareSerial.h, WebServer.h and similar. I remember it took me some time to find all of them, and the right ones. One drawback when using Arduino IDE is that it stores all dependencies for all projects in one location and makes it hard when one work with multiple projects, and even worse if those projects need different version of a dependency.

I know that PlatformIO does this differently, so that each project has its own dependency. In my opinion it is a much better way. Not sure what is common practice, but I imagined that the specific dependencies used in a PlatformIO project could be added to github so that the project in theory should compile immediately after downloading it.

Do you know what is good practice here @netmindz?

**Comment by netmindz** [comment]
Yeah, the "vanilla" Arduino doesn't really have any way of handling project dependencies. Some projects copy 3rd party libraries into their own project, but that's not great. I've tried to use git submodules, but then if people aren't familiar with git they get empty folders.

That's why I swapped the project to PlatformIO, you can then just open and run. OK needs you to install PlatformIO, but if you are a "power" user, of ArduinoIDE, you can just open the sensor/src/sensor.ino file, say yes to rename and fix the deps

**Comment by mbuhansen** [comment]
thank you for your answers. here is attached the log from terminal window.
I have open you project, made wifi.h file i src folder. and try to upload to ESP32, at the end i got code wrong chip, it is like ESP32 not is config in your project.

[Platformio error.txt](https://github.com/netmindz/balboa_GL_ML_spa_control/files/11395593/Platformio.error.txt)
![2023-05-04](https://user-images.githubusercontent.com/91631350/236158711-48afefb9-4f55-49d2-97ef-9a99a2ef32b5.png)

**Comment by mbuhansen** [comment]
[Platformio error.txt](https://github.com/netmindz/balboa_GL_ML_spa_control/files/11395633/Platformio.error.txt)

**Comment by netmindz** [comment]
You are running the wrong build. The D1 mini is an esp8266 profile. Click on the PlatformIO icon on the left, expand the options for the wemos and select upload and monitor

**Comment by netmindz** [comment]
Actually, looks like you are trying to build both targets. 

You definitely only want to be trying to build and upload the target that matches your device.

Why you are seeing compile errors for the dependent library for the esp32 build I'm not sure why.

The project builds correctly in GitHub actions, so there isn't anything magic about my build environment

**Comment by mbuhansen** [comment]
Okay, yes i use build button in the bottom of the screen. 
Now i found the upload and monitor in theplatformio menu, but i get stil lots of errors.
![2023-05-04 (1)](https://user-images.githubusercontent.com/91631350/236278015-21ea0e53-8c4e-4b21-ac34-55787793a633.png)
![2023-05-04 (2)](https://user-images.githubusercontent.com/91631350/236278057-17b24fab-f8e0-48af-9ebc-e74df904f13b.png)

**Comment by netmindz** [comment]
Found the issue @mbuhansen - as you are on windows, it wasn't including the right files

**Comment by mbuhansen** [comment]
Yes i use windows.
But not i works now, app is loaded to ESP32, and can see webserver is online now.
Just to be sure i have to connect pin 19 and 23 from ESP32 to RS485 board.

Many thanks for the help, looking forward to my heating system now can see when the spa heats up...

**Comment by netmindz** [comment]
Does the status page now show the mode and temp? If not try swapping a+b on the rs485 or the rx and tx

**Comment by mbuhansen** [comment]
Yes status display show up. I have not connect to spa yet, it is the next step.
In mqtt i get error because missing username and password from esp32, how can i write this in code.?

**Comment by netmindz** [comment]
Add a #define BROKER_USERNAME and #define BROKER_PASSWORD after BROKER_ADDR

**Comment by mbuhansen** [comment]
This it works great. The esp32 is connected and working, i can see all in home assistant. 
Now i just need a little more test, have problem with weak wifi signal at the hottub.
when you send command to hottub , how are you doing this..??

**Comment by netmindz** [comment]
Great to hear you have the basic read-only setup working. I have a branch called send-command-queue that allows for toggle of the light and going in between standard and eco mode from home assistant. You will also need to connect up pin5 from the tub to the controller as well as make sure your RS485 adapter is connected up correctly to send as well. Personally, I found that I can only send if it's connected to the 5v not 3.3v supply

**Comment by mbuhansen** [comment]
Okay.
Is it the CMD topic i can send message to, if i want to switch mode..???
Do you have a description, how to send command back..??

**Comment by netmindz** [comment]
For the features that can be controlled, they appear as a switch within Home Assistant, so no need to know any codes.

Probably best to continue in the discussion section rather than that in this closed bug report 

https://github.com/netmindz/balboa_GL_ML_spa_control/discussions
